### ISSUE TITLE
IMPORTANT: STMP assumes you have [BasicAuthentication enabled on your ST server]

### ISSUE THREAD

**Issue by BlankFX1** [RossAscends/STMP#20]
`IMPORTANT: STMP assumes you have [BasicAuthentication enabled on your ST server]`
Would you kindly stop assuming that? It's an annoyance not needed for many users.

**Comment by RossAscends** [comment]
Running ST in noCSRF mode and without BasicAuth is just asking for 4chan to scrape your IP and see your logs. It is strongly recommended that you have some kind of barrier to entry. BasicAuth is the least restrictive while still keeping completely random people out.

**Comment by BlankFX1** [comment]
In civilized countries (mostly excluding the US) local machines run behind a firewall and/or a NAT.
admin:admin will suffice then, for now.

**Comment by RossAscends** [comment]
There are automated means to scan random IPs on common ports looking for responses. 

https://www.shodan.io/search?query=SillyTavern

ST's 8000 is a common port, and it is open explicitly if have noCSRF and are allowing remote connections (a common thing people do to acces ST running on their PC while using their phones on the same wifi). ST's whitelist security will suffice as well, but I find BasicAuth to be less restrictive and flexible.

**Comment by BlankFX1** [comment]
I'm not familiar with noCSRF, but if Port 8000 isn't explicitly opened manually or by PCP/UPnP in the routers firewall, it won't be accessible from the internet no matter what is configured on a local machine.

Thats why ST never was accessible from the internet, but always just worked fine when accessed from other devices within our LAN/WLAN aka "Wifi".

We're not planning to access ST/STMP from the outside - and if so, we would do so by using an private VPN.
Am I still missing something?

**Comment by RossAscends** [comment]
CSRF is a security measure that requires the browser accessing ST's server to have a matching randomly generated token/cookie identifier. Only one is allowed at any given time. this prevents connections from multiple devices at once, and from unidentified agents (such as STMP). that's why you need to turn it off when using horde on STMP (because STMP access ST's server to make the  horde requests, and it won't have a CSRF token). however, doing so enables other unidentified agents to connect to the ST server as well. 

you can try kepeing basicAuth off in ST, and just changing the secrets.json's `sillytavern_basic_auth_string` to `""`. that might work. i'll check and make a push real quick that should ensure it will.

**Comment by RossAscends** [comment]
ok it's done. pull and see if it works. however I haven't looked at the horde code in weeks, and there have been big changes elsewhere in the code during that time, so it might not even be working atm.

**Comment by BlankFX1** [comment]
As I went with using Text Generation WebUI as a Backend instead of Horde, I can't really test it fow now.
